version: '3'

services:
  #TODO: Add the react service to the compose
  web:
    image: m0sscr.azurecr.io/devices:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3005:3005 # Ports on 3005 as to not conflict with react server on 3000